FROM ubuntu:xenial

ENV ARCH=x86_64

RUN apt-get update && \
    apt-get install -y \
        gcc g++ clang make cmake libxpm-dev git libcurl4-openssl-dev wget zlib1g-dev libc6-dev bsdmainutils

RUN wget https://artifacts.assassinate-you.net/prebuilt-cmake/continuous/cmake-v3.19.1-ubuntu_xenial-x86_64.tar.gz -O- | \
        tar xz -C /usr/local --strip-components=1

ARG UID
RUN adduser --system --group --uid "$UID" build
USER build

ENV APPIMAGE_EXTRACT_AND_RUN=1
